version: "3.9"

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile.ssr
      args:
        APP_NAME: mainstream-ssr
    ports:
      - "4000:4000"

  seller-backoffice:
    build:
      context: .
      dockerfile: Dockerfile.csr
      args:
        APP_NAME: seller-backoffice
    ports:
      - "4001:80"
